repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "shopy"]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        entry: flake8 shopy
        exclude: ^tests/
#-   repo: https://github.com/pre-commit/mirrors-pylint
#    rev: 'v2.6.0'
#    hooks:
#    -   id: pylint
#        entry: pylint shopy/
#        args: ['--errors-only']
