name: Build & Test on PR

on: pull_request

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"
            - name: Copy environments
              run: cp .env.dist .env
            - name: Install Poetry
              run: pip install poetry
            - name: Install Dependencies
              run: poetry install --with dev
            - name: Run Pre Commit All Files
              run: poetry run pre-commit run --all-files
            - name: Run Tests
              run: poetry run pytest
